version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
    ports:
      - "8070:8070"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: google-places-frontend/Dockerfile.frontend

      args:
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    environment:

      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    ports:
     - "5173:80"
    depends_on:
     - backend


volumes:
  db_data:






#  frontend:
#    build:
#      context: ./google-places-frontend
#      dockerfile: Dockerfile.frontend
#      args:
#        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
#    env_file:
#      - .env
#    ports:
#      - "5173:80"
#    depends_on:
#      - backend


