FROM node:18-alpine as build
WORKDIR /app


ARG VITE_GOOGLE_MAPS_API_KEY
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY


COPY google-places-frontend/google-places-frontend/package*.json ./
RUN npm install


COPY google-places-frontend/google-places-frontend/ ./


RUN npm run build


FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
